name: Create PR TF Plan comment

on: 
    pull_request:
      paths:
        - 'tf/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    name: 'Terraform PR'
    runs-on: ubuntu-latest
    environment: demo
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FABRIC_TENANT_ID: ${{ secrets.FABRIC_TENANT_ID }}
      FABRIC_CLIENT_ID: ${{ secrets.FABRIC_CLIENT_ID }}
      FABRIC_USE_OIDC: ${{ vars.FABRIC_USE_OIDC }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_USE_OIDC: true
      WORKING_DIRECTORY: "./tf"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: '${{ env.WORKING_DIRECTORY }}'
          backend_config: "resource_group_name=${{ vars.TERRAFORM_BACKEND_RG_ORG }} storage_account_name=${{ vars.TERRAFORM_BACKEND_SA_ORG }} container_name=${{ vars.TERRAFORM_BACKEND_CONTAINER }} key=${{ vars.TERRAFORM_BACKEND_KEY_ORG }}"
          variables: |
            tenant_id = "${{ secrets.FABRIC_TENANT_ID }}"
            client_id = "${{ secrets.FABRIC_CLIENT_ID }}"
            arm_client_secret = "${{ secrets.FABRIC_CLIENT_SECRET }}"
            admin_user = "${{ secrets.ADMIN_USER }}"
            azeventhub_saskey = "${{ secrets.AZURE_EVENTHUB_KEY }}"
